###create application

POST http://localhost:3000/application
Content-Type: application/json

{
    "jobId": "67b31f0e-3a1d-485e-8bcc-61570ca071e8",
    "orgId": "a13d33e8-51dc-47ed-bb19-3fc36fde908d",
    "talentId": "0d4a6cb6-d60f-4ee7-aa21-41c7efd1af75"
}

### 
GET http://localhost:3000/application/talent/0d4a6cb6-d60f-4ee7-aa21-41c7efd1af75
Content-Type: application/json

###
GET http://localhost:3000/application/job/67b31f0e-3a1d-485e-8bcc-61570ca071e8
Content-Type: application/json

###
PUT http://localhost:3000/application/98b051d9-0c1a-47c8-9ce2-c3b262e6f0e7

{
     "applicationId": "98b051d9-0c1a-47c8-9ce2-c3b262e6f0e7",
     "status": "PENDING"
}