### 
POST http://localhost:3000/message
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlRhbGVudCIsInRhbGVudElkIjoiMGQ0YTZjYjYtZDYwZi00ZWU3LWFhMjEtNDFjN2VmZDFhZjc1IiwicHJvZmlsZUltZyI6Imh0dHBzOi8vaGFwcHl0cmF2ZWwudmlhamVzL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzA0LzE0Ni0xNDY4NDc5X215LXByb2ZpbGUtaWNvbi1ibGFuay1wcm9maWxlLXBpY3R1cmUtY2lyY2xlLWhkLnBuZyIsImZpcnN0bmFtZSI6Ik1lc2giLCJsYXN0bmFtZSI6IktvcmlyIiwiZW1haWwiOiJtZXNoLmtvcmlyQGV4YW1wbGUuY29tIiwiaW5kdXN0cnlJZCI6ImY0MjkxZjdjLWNmOTMtNGE5My05ZmJlLWI0NGY0MDAwZDk0NCIsInNwZWNpYWxpdHkiOiJXb3JkcHJlc3MgRGVzaWduIiwidGFsZW50V2FsbGV0IjoibWVzaC5rb3Jpci5ldGgiLCJsb2NhdGlvbiI6IkpvaCdidXJnLCBTb3V0aCBBZnJpY2EiLCJwaG9uZSI6Iis5NzEgNCAxMjMgNDU2NyIsImlzV2VsY29tZWQiOm51bGwsImlzVmVyaWZpZWQiOm51bGwsImlhdCI6MTcxMTAwNTQ5MCwiZXhwIjoxNzExMDQxNDkwfQ.usV3ijiyKBYckq5VKxZdGlVFbm-c27lDkoVyGY7rdfU

{
    "orgId":"a13d33e8-51dc-47ed-bb19-3fc36fde908d",
    "talentId":"184bcf5f-de9e-45cd-aac7-1940bd002b30",
    "content":"Work in progress",
    "timestamp":"2022-03-18T14:30:00"
}

### 
GET http://localhost:3000/message/talent/184bcf5f-de9e-45cd-aac7-1940bd002b30
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlRhbGVudCIsInRhbGVudElkIjoiMGQ0YTZjYjYtZDYwZi00ZWU3LWFhMjEtNDFjN2VmZDFhZjc1IiwicHJvZmlsZUltZyI6Imh0dHBzOi8vaGFwcHl0cmF2ZWwudmlhamVzL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDIwLzA0LzE0Ni0xNDY4NDc5X215LXByb2ZpbGUtaWNvbi1ibGFuay1wcm9maWxlLXBpY3R1cmUtY2lyY2xlLWhkLnBuZyIsImZpcnN0bmFtZSI6Ik1lc2giLCJsYXN0bmFtZSI6IktvcmlyIiwiZW1haWwiOiJtZXNoLmtvcmlyQGV4YW1wbGUuY29tIiwiaW5kdXN0cnlJZCI6ImY0MjkxZjdjLWNmOTMtNGE5My05ZmJlLWI0NGY0MDAwZDk0NCIsInNwZWNpYWxpdHkiOiJXb3JkcHJlc3MgRGVzaWduIiwidGFsZW50V2FsbGV0IjoibWVzaC5rb3Jpci5ldGgiLCJsb2NhdGlvbiI6IkpvaCdidXJnLCBTb3V0aCBBZnJpY2EiLCJwaG9uZSI6Iis5NzEgNCAxMjMgNDU2NyIsImlzV2VsY29tZWQiOm51bGwsImlzVmVyaWZpZWQiOm51bGwsImlhdCI6MTcxMTAwNTQ5MCwiZXhwIjoxNzExMDQxNDkwfQ.usV3ijiyKBYckq5VKxZdGlVFbm-c27lDkoVyGY7rdfU


### 
GET http://localhost:3000/message/employer/a13d33e8-51dc-47ed-bb19-3fc36fde908d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlRhbGVudCIsInRhbGVudElkIjoiMTg0YmNmNWYtZGU5ZS00NWNkLWFhYzctMTk0MGJkMDAyYjMwIiwicHJvZmlsZUltZyI6ImV4YW1wbGUuY29tL2ltYWdlLmpwZyIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImluZHVzdHJ5SWQiOiI4ZmU4OGI0ZC01MGQ2LTQ1NDMtYjA4NC1mMWE1Nzk2ODI4MzEiLCJzcGVjaWFsaXR5IjoiTGFuZHNjYXBlIFBob3RvZ3JhcGh5IiwidGFsZW50V2FsbGV0Ijoiam9obmRvZS5ldGgiLCJsb2NhdGlvbiI6IkxvcyBBbmdlbGVzLCBVU0EiLCJwaG9uZSI6IisxIDEyMy00NTYtNzg5MCIsImlzV2VsY29tZWQiOm51bGwsImlzVmVyaWZpZWQiOm51bGwsImlhdCI6MTcxMDg0NTcyMywiZXhwIjoxNzEwODgxNzIzfQ.G8LwFIxuGhb38rGJ_FZrzg2Jt50UUkoUMGPlV8ij_YQ


### 
GET http://localhost:3000/message/session/talent/184bcf5f-de9e-45cd-aac7-1940bd002b30/employer/a13d33e8-51dc-47ed-bb19-3fc36fde908d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlRhbGVudCIsInRhbGVudElkIjoiMTg0YmNmNWYtZGU5ZS00NWNkLWFhYzctMTk0MGJkMDAyYjMwIiwicHJvZmlsZUltZyI6ImV4YW1wbGUuY29tL2ltYWdlLmpwZyIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImluZHVzdHJ5SWQiOiI4ZmU4OGI0ZC01MGQ2LTQ1NDMtYjA4NC1mMWE1Nzk2ODI4MzEiLCJzcGVjaWFsaXR5IjoiTGFuZHNjYXBlIFBob3RvZ3JhcGh5IiwidGFsZW50V2FsbGV0Ijoiam9obmRvZS5ldGgiLCJsb2NhdGlvbiI6IkxvcyBBbmdlbGVzLCBVU0EiLCJwaG9uZSI6IisxIDEyMy00NTYtNzg5MCIsImlzV2VsY29tZWQiOm51bGwsImlzVmVyaWZpZWQiOm51bGwsImlhdCI6MTcxMDg0NTcyMywiZXhwIjoxNzEwODgxNzIzfQ.G8LwFIxuGhb38rGJ_FZrzg2Jt50UUkoUMGPlV8ij_YQ



### 
PUT http://localhost:3000/message/message_id_here/status
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVHlwZSI6IlRhbGVudCIsInRhbGVudElkIjoiMTg0YmNmNWYtZGU5ZS00NWNkLWFhYzctMTk0MGJkMDAyYjMwIiwicHJvZmlsZUltZyI6ImV4YW1wbGUuY29tL2ltYWdlLmpwZyIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImluZHVzdHJ5SWQiOiI4ZmU4OGI0ZC01MGQ2LTQ1NDMtYjA4NC1mMWE1Nzk2ODI4MzEiLCJzcGVjaWFsaXR5IjoiTGFuZHNjYXBlIFBob3RvZ3JhcGh5IiwidGFsZW50V2FsbGV0Ijoiam9obmRvZS5ldGgiLCJsb2NhdGlvbiI6IkxvcyBBbmdlbGVzLCBVU0EiLCJwaG9uZSI6IisxIDEyMy00NTYtNzg5MCIsImlzV2VsY29tZWQiOm51bGwsImlzVmVyaWZpZWQiOm51bGwsImlhdCI6MTcxMDg0NTcyMywiZXhwIjoxNzEwODgxNzIzfQ.G8LwFIxuGhb38rGJ_FZrzg2Jt50UUkoUMGPlV8ij_YQ

{
    "status": "READ"
}
